Traceback (most recent call last):
  File "/gdata/huangzp/hr_regan/main.py", line 41, in <module>
    main(config)
  File "/gdata/huangzp/hr_regan/main.py", line 29, in main
    trainer = Trainer(config, a_data_loader, b_data_loader)
  File "/gdata/huangzp/hr_regan/trainer.py", line 56, in __init__
    self.build_model()
  File "/gdata/huangzp/hr_regan/trainer.py", line 105, in build_model
    conv_dims[-1]/2, b_channel, deconv_dims, self.num_gpu)
  File "/gdata/huangzp/hr_regan/models.py", line 157, in __init__
    self.layers.append(nn.ConvTranspose2d(prev_dim, out_dim, 4, 2, 1, bias=False))
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/conv.py", line 595, in __init__
    True, output_padding, groups, bias)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/conv.py", line 30, in __init__
    in_channels, out_channels // groups, *kernel_size))
TypeError: torch.FloatTensor constructor received an invalid combination of arguments - got (float, int, int, int), but expected one of:
 * no arguments
 * (int ...)
      didn't match because some of the arguments have invalid types: (!float!, !int!, !int!, !int!)
 * (torch.FloatTensor viewed_tensor)
 * (torch.Size size)
 * (torch.FloatStorage data)
 * (Sequence data)

Unexpected end of /proc/mounts line `overlay / overlay rw,relatime,lowerdir=/home/docker-root/overlay2/l/VYEKTA4MZ3NQFF7OCRT6QDGWLU:/home/docker-root/overlay2/l/AZKAXIRQMH7POJIQEDKXQI4FIL:/home/docker-root/overlay2/l/IEHICCHRNWVNEFPDII5V4UOVNJ:/home/docker-root/overlay2/l/M2UN22Y23ISVSR35AGR5F5QUWO:/home/docker-root/overlay2/l/5YEGEGXKBZ23DXJGWNEIPLBSFT:/home/docker-root/overlay2/l/A62L5NEWBDNRKNZ4HZ7L2F2KRL:/home/docker-root/overlay2/l/PMEIESVLUFSJ6KH5NU7B3QG3JB:/home/docker-root/overlay2/l/2Z7A4XNYQPC7MVMVOM4RQMHNVW:/home/docker-root/overla'
Unexpected end of /proc/mounts line `overlay / overlay rw,relatime,lowerdir=/home/docker-root/overlay2/l/ASC76FWWXUWM7X4GAH2C6BXW3T:/home/docker-root/overlay2/l/AZKAXIRQMH7POJIQEDKXQI4FIL:/home/docker-root/overlay2/l/IEHICCHRNWVNEFPDII5V4UOVNJ:/home/docker-root/overlay2/l/M2UN22Y23ISVSR35AGR5F5QUWO:/home/docker-root/overlay2/l/5YEGEGXKBZ23DXJGWNEIPLBSFT:/home/docker-root/overlay2/l/A62L5NEWBDNRKNZ4HZ7L2F2KRL:/home/docker-root/overlay2/l/PMEIESVLUFSJ6KH5NU7B3QG3JB:/home/docker-root/overlay2/l/2Z7A4XNYQPC7MVMVOM4RQMHNVW:/home/docker-root/overla'
/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py:1168: UserWarning: Using a target size (torch.Size([32])) that is different to the input size (torch.Size([32, 1])) is deprecated. Please ensure they have the same size.
  "Please ensure they have the same size.".format(target.size(), input.size()))
Traceback (most recent call last):
  File "/gdata/huangzp/hr_regan/main.py", line 41, in <module>
    main(config)
  File "/gdata/huangzp/hr_regan/main.py", line 33, in main
    trainer.train()
  File "/gdata/huangzp/hr_regan/trainer.py", line 308, in train
    print("[{}/{}] psnr_H: {:.4f} psnr_L: {:.4f}".format(step, self.max_step, psnr_H, psnr_L))
TypeError: unsupported format string passed to Variable.__format__
Unexpected end of /proc/mounts line `overlay / overlay rw,relatime,lowerdir=/home/docker-root/overlay2/l/F4RK7BXNYUFZADI37FVTI2ISYY:/home/docker-root/overlay2/l/AZKAXIRQMH7POJIQEDKXQI4FIL:/home/docker-root/overlay2/l/IEHICCHRNWVNEFPDII5V4UOVNJ:/home/docker-root/overlay2/l/M2UN22Y23ISVSR35AGR5F5QUWO:/home/docker-root/overlay2/l/5YEGEGXKBZ23DXJGWNEIPLBSFT:/home/docker-root/overlay2/l/A62L5NEWBDNRKNZ4HZ7L2F2KRL:/home/docker-root/overlay2/l/PMEIESVLUFSJ6KH5NU7B3QG3JB:/home/docker-root/overlay2/l/2Z7A4XNYQPC7MVMVOM4RQMHNVW:/home/docker-root/overla'
/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py:1168: UserWarning: Using a target size (torch.Size([32])) that is different to the input size (torch.Size([32, 1])) is deprecated. Please ensure they have the same size.
  "Please ensure they have the same size.".format(target.size(), input.size()))
