/usr/local/sbin/startdocker: line 3: /tmp/startdocker.log: Permission denied
/usr/local/sbin/startdocker: line 76: /tmp/startdocker.log: Permission denied
/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py:1168: UserWarning: Using a target size (torch.Size([32])) that is different to the input size (torch.Size([32, 1])) is deprecated. Please ensure they have the same size.
  "Please ensure they have the same size.".format(target.size(), input.size()))
Traceback (most recent call last):
  File "/gdata/huangzp/hr_regan/main.py", line 41, in <module>
    main(config)
  File "/gdata/huangzp/hr_regan/main.py", line 33, in main
    trainer.train()
  File "/gdata/huangzp/hr_regan/trainer.py", line 372, in train
    l_decoder.backward()
  File "/usr/local/lib/python3.6/dist-packages/torch/autograd/variable.py", line 167, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
  File "/usr/local/lib/python3.6/dist-packages/torch/autograd/__init__.py", line 99, in backward
    variables, grad_variables, retain_graph)
RuntimeError: CUDNN_STATUS_EXECUTION_FAILED
Unexpected end of /proc/mounts line `overlay / overlay rw,relatime,lowerdir=/home/docker-root/overlay2/l/C5D6IZJARMWMMXWAQY4XBL2X5J:/home/docker-root/overlay2/l/AHAHQKH36LYJE7RZKPPXGPXBIQ:/home/docker-root/overlay2/l/QAQWZTYDDYV4UX4XBJLVJ6AF4U:/home/docker-root/overlay2/l/HHUJ7KDPU3WM755SK7O3TUFRID:/home/docker-root/overlay2/l/DDTCMDUMHNBWC2L5YOTC3ATBOE:/home/docker-root/overlay2/l/6T4H6OZL7Q4NC3BCRLKAXK7TH7:/home/docker-root/overlay2/l/GHM6KDX2LFVM42KXBY4ZZYLUK4:/home/docker-root/overlay2/l/BIZCJVYOIC7AQ63EQC7ILJSZ3B:/home/docker-root/overla'
/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py:1168: UserWarning: Using a target size (torch.Size([32])) that is different to the input size (torch.Size([32, 1])) is deprecated. Please ensure they have the same size.
  "Please ensure they have the same size.".format(target.size(), input.size()))
